from typing import Iterable, List, Mapping, Sequence

import numpy as np

class CircuitNode:
    id: int

    def __init__(self, id: int) -> None: ...
    def propagate_scope(self) -> None: ...
    def scope_as_list(self) -> List[int]: ...
    def set_scope_from_iterable(self, indices: Iterable[int]) -> None: ...

class CategoricalInputNode(CircuitNode):
    def __init__(
        self,
        id: int,
        scope_var: int,
        probabilities: Sequence[float],
    ) -> None: ...
    def probabilities_list(self) -> List[float]: ...
    def cardinality(self) -> int: ...

class ProductNode(CircuitNode):
    def __init__(self, id: int, children: Sequence[CircuitNode]) -> None: ...
    def children(self) -> List[CircuitNode]: ...

class SumNode(CircuitNode):
    def __init__(
        self,
        id: int,
        children: Sequence[CircuitNode],
        parameters: Sequence[float],
    ) -> None: ...
    def children(self) -> List[CircuitNode]: ...
    def parameters_list(self) -> List[float]: ...

class Evidence:
    def __init__(self, assignment: dict[int, int] | None = None) -> None: ...
    def update_from_mapping(self, assignment: dict[int, int]) -> None: ...

def likelihood(root: CircuitNode, assignment: dict[int, int]) -> float: ...
def log_likelihood(root: CircuitNode, assignment: dict[int, int]) -> float: ...
def sample(
    root: CircuitNode,
    n_samples: int,
    seed: int | None = None,
) -> list[dict[int, int]]: ...

class LogLikelihoodGradients:
    value: float
    sum_grads: dict[int, np.ndarray]
    cat_grads: dict[int, np.ndarray]

def mean_log_likelihood_and_grad(
    root: CircuitNode,
    dataset: Sequence[Mapping[int, int]],
) -> tuple[float, LogLikelihoodGradients]: ...
